const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n||0);
function emi(p,r,y){let i=r/1200,n=y*12;return i?p*i*(1+i)**n/((1+i)**n-1):p/n}
document.querySelectorAll('[data-emi]').forEach(box=>{const go=()=>{let [p,r,y]=[...box.querySelectorAll('input')].map(x=>+x.value);box.querySelector('[data-result]').textContent=money(emi(p,r,y))};box.querySelector('button').onclick=go;go()});
const form=document.querySelector('#applicationForm');if(form)form.onsubmit=e=>{e.preventDefault();let data=Object.fromEntries(new FormData(form));data.id='LE'+Date.now().toString().slice(-8);data.status='Under Review';data.date=new Date().toLocaleDateString('en-IN');localStorage.setItem('loanEaseApplication',JSON.stringify(data));location.href='thank-you.html'};
function app(){try{return JSON.parse(localStorage.getItem('loanEaseApplication'))}catch{return null}}const a=app();
document.querySelectorAll('[data-app]').forEach(x=>{let k=x.dataset.app;x.textContent=k==='amount'?money(a?.amount):a?.[k]||'—'});
const status=document.querySelector('#statusForm');if(status)status.onsubmit=e=>{e.preventDefault();let found=app(),out=document.querySelector('#statusOut');out.innerHTML=found&&status.id.value.trim()===found.id?'<div class="notice">Application <b>'+found.id+'</b> is <b>'+found.status+'</b>.</div>':'<div class="notice">No matching application was found.</div>'};
const login=document.querySelector('#loginForm');if(login)login.onsubmit=e=>{e.preventDefault();localStorage.setItem('loanEaseUser',document.querySelector('#email').value);location.href='my-loan.html'};
const admin=document.querySelector('#adminForm');if(admin)admin.onsubmit=e=>{e.preventDefault();location.href='admin-dashboard.html'};
const loanTypes={personal:{name:'Personal Loan',rate:10.5,years:5,amount:500000,headline:'Personal loan for your personal needs.',description:'Funds for emergencies, travel, weddings, medical expenses and other personal requirements.',benefits:['Flexible loan amount and tenure','Simple online application','Suitable for planned and urgent expenses','Valid identity and income documents']},education:{name:'Education Loan',rate:8,years:10,amount:800000,headline:'Invest in your education.',description:'Financial assistance for higher education, tuition fees, books and eligible educational expenses.',benefits:['Support for higher education','Flexible repayment options','Education-focused financing','Online application tracking']},home:{name:'Home Loan',rate:7.5,years:20,amount:3000000,headline:'Build your dream home.',description:'Finance a property purchase, construction or another eligible housing requirement.',benefits:['Long repayment tenure','Support for larger requirements','Competitive housing finance','Online application tracking']},vehicle:{name:'Vehicle Loan',rate:8.5,years:5,amount:700000,headline:'Drive your next journey.',description:'Finance a new or used car, bike or eligible commercial vehicle.',benefits:['New and used vehicle financing','Flexible tenure options','Quick EMI planning','Simple online application']},business:{name:'Business Loan',rate:11,years:5,amount:1000000,headline:'Give your business room to grow.',description:'Financial support for expansion, equipment, inventory and working capital.',benefits:['Business expansion funding','Working-capital support','Equipment purchase finance','Flexible repayment tenure']}};
const loanPage=document.querySelector('[data-loan-page]');if(loanPage){const key=new URLSearchParams(location.search).get('type')||'personal',loan=loanTypes[key]||loanTypes.personal;document.title=loan.name+' | LoanEase';document.querySelectorAll('[data-loan]').forEach(el=>{const value=loan[el.dataset.loan];if(Array.isArray(value))el.innerHTML=value.map(item=>'<li>'+item+'</li>').join('');else if(value!==undefined)el.textContent=value});document.querySelector('[data-loan="rate"]').textContent=loan.rate+'%';document.querySelector('[data-loan="tenure"]').textContent=key==='home'?'10–30 years':key==='education'?'5–15 years':key==='vehicle'?'1–7 years':key==='business'?'1–8 years':'1–5 years';document.querySelector('[data-loan="amount"]').value=loan.amount;document.querySelector('[data-loan="rateInput"]').value=loan.rate;document.querySelector('[data-loan="years"]').value=loan.years;document.querySelector('[data-loan="apply"]').href='apply.html?loan='+encodeURIComponent(loan.name);document.querySelector('[data-emi] button').click()}
const loanSelect=document.querySelector('select[name="loan"]');if(loanSelect){const requested=new URLSearchParams(location.search).get('loan');if([...loanSelect.options].some(option=>option.value===requested))loanSelect.value=requested}
const themeBtn=document.querySelector('#themeBtn');const setTheme=dark=>{document.body.classList.toggle('dark',dark);if(themeBtn)themeBtn.textContent=dark?'☀️':'🌙'};setTheme(localStorage.getItem('loanEaseTheme')==='dark');if(themeBtn)themeBtn.onclick=()=>{const dark=!document.body.classList.contains('dark');setTheme(dark);localStorage.setItem('loanEaseTheme',dark?'dark':'light')};
